# Generated by Django 4.2 on 2024-03-03 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_tag_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(220, 'Body requires minimum 220 characters.')]),
        ),
    ]
