# Generated by Django 4.2 on 2024-03-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accepted_answer_for',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answer', to='questions.question'),
        ),
    ]
