# Generated by Django 4.2 on 2024-03-05 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_answer_accepted_answer_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='answer_save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='question_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
