# Generated by Django 4.2 on 2024-03-05 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0010_question_down_votes_question_up_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='down_votes',
            field=models.ManyToManyField(blank=True, related_name='ans_down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='ans_up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
