# Generated by Django 4.2 on 2024-03-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_bounty_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
