# Generated by Django 4.2 on 2024-03-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
